
class Ball :
    """
    This is a ball model
    """

    def __init__(self):
        self.data = {'ext_func_call': None, 'comp_annotation': None, 'eq_section': [{'init': False, 'eqs': ['x(t).diff(t) - v_x', 'y(t).diff(t) - v_y', 'v_x(t).diff(t) - -c * x + f_x', 'v_y(t).diff(t) - -c * y + f_y']}], 'language_spec': None, 'ext_annotation': None, 'elist': [{'constraining_clause': None, 'comment': None, 'redeclare': False, 'outer': False, 'inner': False, 'rclassdef': None, 'comp': None, 'rcomp': None, 'final': False, 'classdef': {'type_prefix': [u'input'], 'type_specifier': u'Real', 'array_subscripts': None, 'component_list': ['f_x', 'f_y']}}, {'constraining_clause': None, 'comment': None, 'redeclare': False, 'outer': False, 'inner': False, 'rclassdef': None, 'comp': None, 'rcomp': None, 'final': False, 'classdef': {'type_prefix': [u'parameter'], 'type_specifier': u'Real', 'array_subscripts': None, 'component_list': ['c']}}, {'constraining_clause': None, 'comment': None, 'redeclare': False, 'outer': False, 'inner': False, 'rclassdef': None, 'comp': None, 'rcomp': None, 'final': False, 'classdef': {'type_prefix': [u'output'], 'type_specifier': u'Real', 'array_subscripts': None, 'component_list': ['x']}}, {'constraining_clause': None, 'comment': None, 'redeclare': False, 'outer': False, 'inner': False, 'rclassdef': None, 'comp': None, 'rcomp': None, 'final': False, 'classdef': {'type_prefix': [u'output'], 'type_specifier': u'Real', 'array_subscripts': None, 'component_list': ['y']}}, {'constraining_clause': None, 'comment': None, 'redeclare': False, 'outer': False, 'inner': False, 'rclassdef': None, 'comp': None, 'rcomp': None, 'final': False, 'classdef': {'type_prefix': [u'output'], 'type_specifier': u'Real', 'array_subscripts': None, 'component_list': ['v_x']}}, {'constraining_clause': None, 'comment': None, 'redeclare': False, 'outer': False, 'inner': False, 'rclassdef': None, 'comp': None, 'rcomp': None, 'final': False, 'classdef': {'type_prefix': [u'output'], 'type_specifier': u'Real', 'array_subscripts': None, 'component_list': ['v_y']}}], 'alg_section': [], 'elist_protected': [], 'elist_public': []}
        pass

