[build-system]
requires = ["setuptools", "versioneer[toml]==0.29"]
build-backend = "setuptools.build_meta"

# See the docstring in versioneer.py for instructions. Note that after changing
# this section, run `versioneer install --no-vendor`, commit the results.

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "src/pymoca/_version.py"
versionfile_build = "pymoca/_version.py"
tag_prefix = ""
parentdir_prefix = "pymoca-"
