class IterativeSimplificationLarge
  Real a;
  Real b;
  Real c;
  Real d;
  Real e;
  Real f;
  parameter Real A(start = 1.0) = 1000.0;
  Real g;
  Real h;
  Real i;
  Real l;
  Real m;
  Real n;
  parameter Real B(min = 0.0, start = 288.15, nominal = 300.0) = D;
  Real o;
  Real p(min = 0.0, start = 288.15, nominal = 300.0);
  parameter Real C;
  parameter Real D(min = 0.0, start = 288.15, nominal = 300.0) = 300.15;
  parameter Real E;
  Real q;
  Real r;
  Real s;
  Real t;
  Real u;
  Real v;
  Real z;
  Real aa;
  Real ab;
  Real ac;
  Real ad;
  Real ae;
  parameter Real F(start = 1.0) = 1000.0;
  Real af;
  Real ag;
  Real ah;
  Real ai;
  Real al;
  Real am;
  parameter Real G(min = 0.0, start = 288.15, nominal = 300.0) = I;
  Real an;
  Real ao(min = 0.0, start = 288.15, nominal = 300.0);
  parameter Real H;
  parameter Real I(min = 0.0, start = 288.15, nominal = 300.0) = 300.15;
  parameter Real L;
  Real ap;
  Real aq(min = 0.4, max = 0.95, start = 0.7, fixed = true);
  Real ar;
  Real as;
  Real at;
  Real av;
  Real au;
  Real az;
  Real ba;
  Real bb;
  Real bc;
  Real bd;
  Real be;
  Real bf;
  Real bg;
  Real bh;
  Real bi;
  Real bl;
  Real bm;
  Real bn;
  Real bo;
  Real bp;
  Real bq;
  Real br;
  input Real P(start = 1000.0);
  input Real Q(min = -400000.0, max = 400000.0, start = 500.0);
  Real bs;
  Real bt;
  Real bu;
  Real bv;
  parameter Real M = 183.0;
  parameter Real N(min = 0.0) = 0.92;
  parameter Real O(min = 0.0) = N;
  Real bz;
  input Real R(min = 0.0, max = 200000.0, start = 500.0);
  Real ca;
  Real cb(min = 0.0);
equation
  a = A;
  a = c - e;
  0.0 = d + f;
  b = d;
  q = C * (1.0 + E * (p - D));
  g = q * h;
  o = g * h;
  g = i - m;
  0.0 = l + n;
  h = l;
  p = B;
  z = F;
  z = ab - ad;
  0.0 = ac + ae;
  aa = ac;
  ap = H * (1.0 + L * (ao - I));
  af = ap * ag;
  an = af * ag;
  af = ah - al;
  0.0 = ai + am;
  ag = ai;
  ao = G;
  ar = 0.0;
  der(aq) = 3.584740913483079e-06 * t;
  r = s - u;
  at = az;
  av + at = au + bb;
  av = ba;
  bi = (-bc) * bd;
  bc = be - bg;
  0.0 = bf + bh;
  bd = bf;
  br = (-bl) * bm;
  bl = bn - bp;
  0.0 = bo + bq;
  bm = bo;
  bs = 0.0;
  bv + min(bu * N - M, bu / O - M) = 0.0;
  bz = bu + bv;
  cb = ca;
  d + bf = 0.0;
  f + l + bt = 0.0;
  n + bh = 0.0;
  t + bo = 0.0;
  v + bq = 0.0;
  (-t) + ac = 0.0;
  ae + ai + as = 0.0;
  (-v) + am = 0.0;
  ab = s;
  ah = ad;
  ah = ar;
  al = u;
  at + br = 0.0;
  av + bv = 0.0;
  bb + ca = 0.0;
  bi + bu = 0.0;
  Q = az;
  au = P;
  s = bn;
  u = bp;
  i = e;
  i = bs;
  bg = m;
  be = c;
  R = ba;
end IterativeSimplificationLarge;
